---
title: "Airbnb Final Project"
author: "Divya Khandke and Adam Ghazzawi"
date: "11/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidycensus)
library(sf)
library(spdep)
library(caret)
library(ckanr)
library(FNN)
library(stargazer)
library(grid)
library(gridExtra)
library(ggcorrplot)
library(dplyr)
library(mapview)
library(jtools)
library(ggmap)
library(RColorBrewer)
library(wesanderson)
library(viridis)
library(broom)
library(rmarkdown)
library(knitr)
library(kableExtra)
```

```{r warning=FALSE, include=FALSE}
#######################
#LOADING SET UP PART 2
######################
mapTheme <- function(base_size = 12) {
  theme(
    text = element_text( color = "black"),
    plot.title = element_text(size = 14,colour = "black"),
    plot.subtitle=element_text(face="italic"),
    plot.caption=element_text(hjust=0),
    axis.ticks = element_blank(),
    panel.background = element_blank(),axis.title = element_blank(),
    axis.text = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(colour = "black", fill=NA, size=2)
  )
}

plotTheme <- function(base_size = 12) {
  theme(
    text = element_text( color = "black"),
    plot.title = element_text(size = 14,colour = "black"),
    plot.subtitle = element_text(face="italic"),
    plot.caption = element_text(hjust=0),
    axis.ticks = element_blank(),
    panel.background = element_blank(),
    panel.grid.major = element_line("grey80", size = 0.1),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(colour = "black", fill=NA, size=2),
    strip.background = element_rect(fill = "grey80", color = "white"),
    strip.text = element_text(size=12),
    axis.title = element_text(size=12),
    axis.text = element_text(size=10),
    plot.background = element_blank(),
    legend.background = element_blank(),
    legend.title = element_text(colour = "black", face = "italic"),
    legend.text = element_text(colour = "black", face = "italic"),
    strip.text.x = element_text(size = 14)
  )
}

palette5 <- c("#FFF717", "#E8BC1C", "#FFAE2B",   "#E86E23", "#FF5940")
palette4 <- c( "#53AAEE", "#438AC3", "#306490" , "#1F4363", "#16314B")
               

#Set up quintile breaks for map legends
qBr <- function(df, variable, rnd) {
  if (missing(rnd)) {
    as.character(quantile(round(df[[variable]],0),
                          c(.01,.2,.4,.6,.8), na.rm=T))
  } else if (rnd == FALSE | rnd == F) {
    as.character(formatC(quantile(df[[variable]]), digits = 3),
                 c(.01,.2,.4,.6,.8), na.rm=T)
  }
}

q5 <- function(variable) {as.factor(ntile(variable, 5))}

nn_function <- function(measureFrom,measureTo,k) {
  measureFrom_Matrix <- as.matrix(measureFrom)
  measureTo_Matrix <- as.matrix(measureTo)
  nn <-   
    get.knnx(measureTo, measureFrom, k)$nn.dist
  output <-
    as.data.frame(nn) %>%
    rownames_to_column(var = "thisPoint") %>%
    gather(points, point_distance, V1:ncol(.)) %>%
    arrange(as.numeric(thisPoint)) %>%
    group_by(thisPoint) %>%
    summarize(pointDistance = mean(point_distance)) %>%
    arrange(as.numeric(thisPoint)) %>% 
    dplyr::select(-thisPoint) %>%
    pull()
  
  return(output)  
}
```


```{r, echo=FALSE,warning=FALSE,message=FALSE,error=FALSE, results='hide',fig.keep='all', results='asis'}
#######################
# Data Loading Part 1 
######################
districts <- read_sf("https://maps.amsterdam.nl/open_geodata/geojson.php?KAARTLAAG=GEBIED_STADSDELEN&THEMA=gebiedsindeling") 

neighborhoods <- read_sf("https://maps.amsterdam.nl/open_geodata/geojson.php?KAARTLAAG=GEBIED_BUURTEN&THEMA=gebiedsindeling")

zipcode4 <- read_sf("https://maps.amsterdam.nl/open_geodata/geojson.php?KAARTLAAG=PC4_BUURTEN&THEMA=postcode")

land_use <- read_sf("https://maps.amsterdam.nl/open_geodata/geojson.php?KAARTLAAG=GRONDGEBRUIK_2017&THEMA=grondgebruik")

student_housing <- read_sf("https://maps.amsterdam.nl/open_geodata/geojson.php?KAARTLAAG=JONGERENSTUDENTENHUISVESTING&THEMA=jongerenstudentenhuisvesting")

overnight <- read_sf("https://maps.amsterdam.nl/open_geodata/geojson.php?KAARTLAAG=OVERNACHTINGSBELEID&THEMA=overnachtingsbeleid")

green_roofs <- read_sf("https://maps.amsterdam.nl/open_geodata/geojson.php?KAARTLAAG=GROENE_DAKEN&THEMA=groene_daken")

parks <- st_read("https://maps.amsterdam.nl/open_geodata/geojson.php?KAARTLAAG=PARKPLANTSOENGROEN&THEMA=stadsparken")

farming <- read_sf("https://maps.amsterdam.nl/open_geodata/geojson.php?KAARTLAAG=STADSLANDBOUW_PUNT&THEMA=stadslandbouw")

maj_streets <- read_sf("https://maps.amsterdam.nl/open_geodata/geojson.php?KAARTLAAG=STADSSTRAAT&THEMA=stadsstraat")

metro_lines <- read_sf("https://maps.amsterdam.nl/open_geodata/geojson.php?KAARTLAAG=TRAMMETRO_LIJNEN_2020&THEMA=trammetro")

metro_stops <- read_sf("https://maps.amsterdam.nl/open_geodata/geojson.php?KAARTLAAG=TRAMMETRO_PUNTEN_2020&THEMA=trammetro")

walkability <- read_sf("https://maps.amsterdam.nl/open_geodata/geojson.php?KAARTLAAG=WALKABILITY&THEMA=walkability")

hist_build <- read_sf("https://maps.amsterdam.nl/open_geodata/geojson.php?KAARTLAAG=HISTORISCHE_BEBOUWING&THEMA=archeologie")

wall_art <- read_sf("https://maps.amsterdam.nl/open_geodata/geojson.php?KAARTLAAG=WANDKUNST&THEMA=wandkunst")

barbecue <- read_sf("https://maps.amsterdam.nl/open_geodata/geojson.php?KAARTLAAG=BBQ&THEMA=bbq")

dog_park <- read_sf("https://maps.amsterdam.nl/open_geodata/geojson.php?KAARTLAAG=HONDEN_SPEELPLAATS&THEMA=honden")

markets <- read_sf("https://maps.amsterdam.nl/open_geodata/geojson.php?KAARTLAAG=MARKTEN&THEMA=markten")

playgrounds <- read_sf("https://maps.amsterdam.nl/open_geodata/geojson.php?KAARTLAAG=SPORT_OPENBAAR&THEMA=sport")

swim <- read_sf("https://maps.amsterdam.nl/open_geodata/geojson.php?KAARTLAAG=ZWEMWATER&THEMA=zwemwater")


```


``` {r}
plot(zipcode4)
```


